// This file is auto-generated by the generate_icon_values.py script. Do not edit manually.
// Generated on: 2026-05-02T22:23:04.349694

import type { IconName } from '@types'
import {
  User,
  Code,
  Github,
  JavaScript,
  Leaflet,
  Check,
  Loading,
  Mail,
  LinkedIn,
  MongoDB,
  NextJS,
  NodeJS,
  OpenAI,
  Preview,
  React,
  Resume,
  Supabase,
  TypeScript,
  Cross,
  ArrowDiagonal,
  Chevron,
  Bolt,
  Home,
  Menu,
  Copy,
  Arrow,
  Express,
  Python,
  PythonWhite,
  Zod,
  TailwindCSS,
  CSS,
  Briefcase,
} from '@consts'

export const iconsMap = {
  'user': User,
  'code': Code,
  'github': Github,
  'java-script': JavaScript,
  'leaflet': Leaflet,
  'check': Check,
  'loading': Loading,
  'mail': Mail,
  'linked-in': LinkedIn,
  'mongo-db': MongoDB,
  'next-js': NextJS,
  'node-js': NodeJS,
  'open-ai': OpenAI,
  'preview': Preview,
  'react': React,
  'resume': Resume,
  'supabase': Supabase,
  'type-script': TypeScript,
  'cross': Cross,
  'arrow-diagonal': ArrowDiagonal,
  'chevron': Chevron,
  'bolt': Bolt,
  'home': Home,
  'menu': Menu,
  'copy': Copy,
  'arrow': Arrow,
  'express': Express,
  'python': Python,
  'python-white': PythonWhite,
  'zod': Zod,
  'tailwind-css': TailwindCSS,
  'css': CSS,
  'briefcase': Briefcase,
}

interface Props extends Omit<React.SVGProps<SVGSVGElement>, 'name'> {
  name: IconName
}

export const Icon = ({ name, ...props }: Props) => {
  const Component = iconsMap[name]
  return <Component {...props} />
}

