from pathlib import Path
from datetime import datetime
import re

"""Generates a TypeScript type definition file for icon names based on the SVG files in the public/icons directory. """


def main() -> None:
    """Generates a TypeScript type definition file for icon names based on the SVG files in the public/icons directory."""

    repo_root = Path(__file__).resolve().parents[1]
    icons_path = repo_root / "src" / "consts" / "icons.tsx"

    names_map = []

    with icons_path.open("r", encoding="utf-8") as f:
        content = f.read()

        # Find all lines that match the pattern of icon definitions, e.g., "export const IconName = () => { ... }"
        regex_pattern = r"export const (\w+)\s*="
        icon_names: list[str] = re.findall(regex_pattern, content)

        for icon_name in icon_names:
            upper_streak = 0
            parsed_name = ""

            # Convert from PascalCase to kebab-case
            for index, char in enumerate(icon_name):
                next_char = icon_name[index + 1] if index + 1 < len(icon_name) else ""

                if char.isupper():
                    upper_streak += 1

                    if parsed_name and (
                        upper_streak <= 1 or (next_char and not next_char.isupper())
                    ):
                        parsed_name += "-"

                    parsed_name += char.lower()
                else:
                    upper_streak = 0
                    parsed_name += char

            names_map.append(
                {
                    "component": icon_name,
                    "key": parsed_name,
                }
            )

    # Generate the TypeScript file content
    output_file = repo_root / "src" / "components" / "icons.tsx"

    content = (
        "// This file is auto-generated by the generate_icon_values.py script. Do not edit manually.\n// Generated on: "
        + datetime.now().isoformat()
        + "\n\n"
    )

    # Import statements
    content += "import type { IconName } from '@types'\n"
    content += "import {\n"
    for name in names_map:
        content += f"  {name['component']},\n"
    content += "} from '@consts'\n\n"

    # Define a const map
    content += "export const iconsMap = {\n"
    for name in names_map:
        content += f"  '{name['key']}': {name['component']},\n"
    content += "}\n\n"

    # Define the Props type
    content += "interface Props extends Omit<React.SVGProps<SVGSVGElement>, 'name'> {\n"
    content += "  name: IconName\n"
    content += "}\n\n"

    # Define the icons component
    content += "export const Icon = ({ name, ...props }: Props) => {\n"
    content += "  const Component = iconsMap[name]\n"
    content += "  return <Component {...props} />\n"
    content += "}\n\n"

    # Write the content to the output file
    with output_file.open("w", encoding="utf-8") as f:
        f.write(content)


if __name__ == "__main__":
    main()
